$(document).ready(() => {

  const tableHtml = ('<tr class="row2"><td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Engelsk</td><td class="grade-col"><ul class="grade"><li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul></td><td class="eksamen-col"><ul class="eksamen"><li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul></td><td class="remove-btn"><i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row2"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Geografi</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td>');
  const tableHtml2 = ('<td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row3"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Matematikk 1T</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row4"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Naturfag</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li>');
  const tableHtml3 = ('<li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row5"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Samfunnsfag</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row6"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Historie</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td>');
  const tableHtml4 = ('<td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row7"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Religion</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row8"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Kroppsøving</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li>');
  const tableHtml5 = ('<li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row9"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Norsk hovedmål, skriftlig</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row10"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">');
  const tableHtml6 = ('Norsk hovedmål, muntlig</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr><tr class="row11"> <td class="active-fag" id="fellesfag-fag" value="0" type="fellesfag">Norsk sidemål</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i>');
  const tableHtml7 = ('</td></tr><tr class="row12"> <td class="activefag" id="fellesfag-fag" value="0" type="fellesfag">Fremmedspråk nivå II</td><td class="grade-col"> <ul class="grade"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="eksamen-col"> <ul class="eksamen"> <li value="1">1</li><li value="2">2</li><li value="3">3</li><li value="4">4</li><li value="5">5</li><li value="6">6</li></ul> </td><td class="remove-btn"> <i class="fas fa-times fa-2x x-btn"></i> </td></tr>');

  $('.table-fellesfag').append(tableHtml + tableHtml2 + tableHtml3 + tableHtml4 + tableHtml5 + tableHtml6 + tableHtml7);

})
